#!/system/bin/sh
# input in mV, resolution of 50 mV
MAX_CHARGE_CURRENT="$1"
DEC_VALUE="$(($MAX_CHARGE_CURRENT/50))"
HEX_VALUE=`printf '%x\n' "$DEC_VALUE"`
echo "0xb9 0x$HEX_VALUE" > /sys/class/power_supply/max77705-charger/data
echo $HEX_VALUE
